### ISSUE TITLE
Sideloaded UWP apps can't use crash reporting

### ISSUE THREAD

**Issue by nbevans** [microsoft/appcenter-sdk-dotnet#725]
### **Description**

UWP apps which are sideloaded such as LOB apps can't seem to receive any crash reports. [Documentation](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/uwp) even states:
> Crash reporting on Windows requires the app to be distributed through the Microsoft Store.

But it gives no explanation as to the logic behind this decision.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create a UWP app and wire up using `AppCenter.Start("<key>", typeof(Crashes))`
2. Make the app crash with an exception of any kind.
3. Observe that AppCenter UI doesn't report the crash at all - even if you restart the app several times, and wait many hours even days.

### ***Expected Behavior**

The crash should be reported on the AppCenter UI. Sideloaded apps are increasingly treated as a first-class citizen in Win10 APIs and this should follow through to crash reporting. Testing of apps is often done via sideloading as well - and without crash reporting - such testing is made many times more difficult. It is slowing down the UWP development track and thus surely harming Microsoft's ambitions for UWP as a platform.

**Comment by clpolet** [comment]
Hi there,
Thanks for reaching us. It's a known technical limitation. Let me ask around.

**Comment by nbevans** [comment]
We've ported our sideloaded Android app to UWP and the AppCenter crash reports (and Xamarin Insights before that) worked fine on Android.

As an example of another area of UWP that has improved its sideloading story: WNS push notifications in FCE added support for sideloaded apps by using "alternate channels / VAPID / WebPush".

Maybe if Watson / AppCenter signed the error reports with the UWP manifest public key then AppCenter could be setup with the private key so it could then securely retrieve the crash reports from Watson.

**Comment by elamalani** [comment]
@nbevans Thanks for your feedback. Currently, we don't support this scenario, but for visibility, we will keep this thread open and let you know once we support it in App Center.

**Comment by helzgate** [comment]
What else doesn't work with side-loaded UWP?  This might be a good place to lay it out.  It appears distribute isn't working unless I'm doing something wrong.

**Comment by xpetrik** [comment]
It is funny that AppCentre itself use sideloading for app distribution to testers. But testers are unable to send crash report back to the AppCentre.

This is a reason why we must use package flights in DevCenter. Distribution thru AppCentre is half-baked.

**Comment by nbevans** [comment]
@xpetrik Indeed - the whole system is broken. Side-loading with full crash dumps needs to be a priority 1. But I fear that because it spans at least 2 distinct teams in Microsoft that we will be waiting for a long time.

**Comment by nbevans** [comment]
@DanieleScipioni As it stands AppCenter is not a like-for-like replacement for neither HockeyApp nor Xamarin Insights. Since side-loading is the #1 way to distribute internal/beta builds, it boggles the mind as to why a crash dump tool such as AppCenter does not support side-loading properly.

**Comment by winnieli1208** [comment]
Hi all,

We have committed to support crash reporting for sideloaded UWP apps before the HockeyApp shutdown. You can follow our [roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap) and [iteration plan](https://github.com/Microsoft/appcenter/wiki/Iteration-plans) to see what our team is working on each month. I expect the Windows work to be started around April and will keep everyone updated. Thanks for the patience!

**Comment by atiyka** [comment]
Hi, is there any update on this thread?

We submitted our app to the store (to a private audience), but even there the crash reporting is not working. The api is connected well (the analytics data are received correctly), the `Crashes.IsEnabledAsync()` returns true, and the `Crashes.SentErrorReport` callback is called when the app starts after the crash had happened. So I think the problem is not at our side.

I read the following [here](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/uwp): _Crash reporting on Windows requires the app to be distributed through the Microsoft Store._ This means that the app should be published to public audience? Or it should work also if it's published just to a private audience?

Thank you!

**Comment by xpetrik** [comment]
> Hi, is there any update on this thread?
> 
> We submitted our app to the store (to a private audience), but even there the crash reporting is not working. The api is connected well (the analytics data are received correctly), the `Crashes.IsEnabledAsync()` returns true, and the `Crashes.SentErrorReport` callback is called when the app starts after the crash had happened. So I think the problem is not at our side.
> 
> I read the following [here](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/uwp): _Crash reporting on Windows requires the app to be distributed through the Microsoft Store._ This means that the app should be published to public audience? Or it should work also if it's published just to a private audience?
> 
> Thank you!

Hi @atiyka,
i check iteration plans every month and there is no information about this. AppCenter developers (leaders) prefer new functions against fix this problem. @winnieli1 wrote someting about April.  Unfortunately this date is completely out of reality. 👎

**Comment by DanieleScipioni** [comment]
Hi,
40 days left to the end of  HockeyApp transitions into App Center, and this is still an issue.
@winnieli1 can you please give some news about that?
From the roadmap (https://github.com/Microsoft/appcenter/wiki/Roadmap) I see that "Diagnostics Support sideloaded UWP apps" is currently an on going work. My feeling is that we will have something, but very late.

**Comment by JasperE84** [comment]
On the 9th of July, Winnie provided me this update: 

> Hello,
>  
> This is Winnie from the App Center PM team. You’re receiving this e-mail because you have access to a UWP app in App Center. I'm excited to announce some upcoming improvements in App Center's UWP crash reporting. Our team is working to add diagnostics support for non-store UWP apps and implementing additional features such as attachments, search, and better crash analytics.
>  
> As we're improving our product to deliver a better experience for you, we ask that you keep your App Center SDK version as 2.1.1 or earlier. We'll be releasing a new Windows preview SDK later this month for WPF and WinForms apps and it's important that you don't upgrade to this SDK for your UWP apps, as we will no longer be able to process your UWP crashes. This preview SDK is for WPF and WinForms apps only.
>  
> **We're excited to bring App Center's UWP crashes support in line with the other supported platforms. When we release this new experience in September 2019, you'll also notice some changes in the UI and a new set of APIs to fully utilize the App Center diagnostic feature set.** I'll proactively reach out when these changes are about to happen.
>  
> If you have any questions please don't hesitate to reach out!
>  
> Best,
> Winnie
>

**Comment by winnieli1** [comment]
Hi @DanieleScipioni - we are actively working on UWP support for non sideloaded apps which will ship with this month's SDK release (in a few weeks). We will _not__  shut down HockeyApp until the items on our roadmap are complete. 

Thanks!

**Comment by jamers99** [comment]
Very keen on having this feature!

**Comment by atiyka** [comment]
Hi @winnieli1, I have two questions:
1. we already migrated our project from hockeyApp to the App Center. Is it possible to migrate back to the hockeyApp until this feature will be done?

2. I read the following [in the docs](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/uwp): `Crash reporting on Windows requires the app to be distributed through the Microsoft Store.` This means that the app should be published to public audience? Or it should work also if it's published just to a private audience?

Thanks for the answer!

**Comment by winnieli1** [comment]
Yep, our target date is sometime next week! We're adding diagnostics support (crashes and handled exceptions) for sideloaded UWP apps in our next SDK release (2.5.0).

**Comment by winnieli1** [comment]
Hi all! We just enabled diagnostics support for sideloaded UWP apps last week with the 2.5.0 SDK release. You can find the docs here: https://docs.microsoft.com/en-us/appcenter/sdk/crashes/uwp 

Thanks for everyone's patience!
